### ISSUE TITLE
softwareApplication schema in UnmannedAerialVehicleTMS

### ISSUE THREAD

**Issue by isalvadori** [smart-data-models/dataModel.UnmannedAerialVehicle#1]
Hi, 
 in the model for UnmannedAerialVehicleTMS there is this definition of the `softwareApplication` attribute:

```
softwareApplication:
      description: ""
      properties:
        applicationCategory:
          type: string
        operatingSystem:
          type: string
        softwareVersion:
          type: string
      type: object
      x-ngsi:
        model: 'Details about the software application using the Schema.org definition https://schema.org/SoftwareApplication'
        type: Property
```
It's not clear whether the three properties listed are the only ones for this object, or since, according to the x-ngsi model this should be built accordingly to https://schema.org/SoftwareApplication, it can then have all the attributes listed in https://schema.org/SoftwareApplication.
